"""Promoted regressions for #234: E10 proposals record the execution that actually ran.

A participant whose provider cannot be constructed must not yield a proposal
attributed to that participant's model, and a proposal's generating model is
the model the executing adapter reports (CI-011 Nondeterministic Audit
Record). Commit b9d615e preserves the negative versions; the repair
demonstrated strict unexpected passes before the expected failures were removed.
No network: unconnected participants use the hermetic default registry;
connected ones use an in-process fake.
"""
from __future__ import annotations

import sqlite3
from types import SimpleNamespace

from hermeneia.narrative.artist_providers import NullArtistProvider
from hermeneia.narrative.provider_registry import ProviderDefinition, ProviderRegistration, ProviderRegistry
from hermeneia.web.app import create_app
from test_explorer_discovery import _seed_discover_db


READING = "A reading generated by the fake executing model."


class MisattributedExecution(AssertionError):
    """Only the observed misattribution failures are expected here."""


class FakeOpenAI:
    """OpenAI-shaped adapter: real `_call_provider` path, no network."""

    def __init__(self, model: str | None = None, **_kwargs):
        self._model = model or "gpt-4o"
        self._client = SimpleNamespace(chat=SimpleNamespace(completions=SimpleNamespace(create=self._create)))

    @staticmethod
    def _create(*, messages, **_kwargs):
        bucketing = "Return the bucket JSON now." in messages[-1]["content"]
        content = '{"buckets": [{"indices": [1, 2]}]}' if bucketing else READING
        return SimpleNamespace(choices=[SimpleNamespace(message=SimpleNamespace(content=content))])

    def execution_config(self) -> dict:
        return {"provider": "openai", "model_id": "fake-gpt-actual", "max_tokens": 512}


def _registry() -> ProviderRegistry:
    def definition(identifier: str) -> ProviderDefinition:
        return ProviderDefinition(id=identifier, display_name=identifier, provider_type="artist", enabled=True,
                                  capabilities=("text",), local_or_remote="remote", default_model="gpt-4o")
    return ProviderRegistry((ProviderRegistration(definition("openai"), FakeOpenAI),
                             ProviderRegistration(definition("null"), NullArtistProvider)))


def _attributions(db) -> list[tuple[str, str]]:
    return list(sqlite3.connect(db).execute(
        "SELECT p.perspective, a.generating_model FROM proposed_interpretations p "
        "JOIN ai_provenance a ON a.id = p.ai_provenance_id ORDER BY p.perspective"))


def test_generate_with_unconnected_participants_creates_no_attributed_proposals(tmp_path):
    db, ids = _seed_discover_db(tmp_path)
    response = create_app(db_path=db).test_client().post(
        "/api/e10/interpretations/generate", json={"observation_id": ids["obs_id"], "participants": ["gpt", "claude"]})
    if response.status_code < 400 or _attributions(db):
        raise MisattributedExecution(f"{response.status_code} {_attributions(db)}")


def test_discover_with_unconnected_participant_creates_no_attributed_proposals(tmp_path):
    db, ids = _seed_discover_db(tmp_path)
    response = create_app(db_path=db).test_client().post(
        "/api/e10/interpretations/discover",
        json={"observation_ids": [ids["obs_id"], ids["obs2_id"]], "participants": ["claude"]})
    if response.status_code < 400 or _attributions(db):
        raise MisattributedExecution(f"{response.status_code} {_attributions(db)}")


def test_generating_model_is_the_executing_adapters_model(tmp_path):
    db, ids = _seed_discover_db(tmp_path)
    response = create_app(db_path=db, provider_registry=_registry()).test_client().post(
        "/api/e10/interpretations/generate", json={"observation_id": ids["obs_id"], "participants": ["gpt"]})
    assert response.status_code == 201, response.get_data(as_text=True)
    if _attributions(db) != [("GPT", "fake-gpt-actual")]:
        raise MisattributedExecution(f"{_attributions(db)}")


def test_connected_participant_creates_its_proposal(tmp_path):
    db, ids = _seed_discover_db(tmp_path)
    response = create_app(db_path=db, provider_registry=_registry()).test_client().post(
        "/api/e10/interpretations/discover",
        json={"observation_ids": [ids["obs_id"], ids["obs2_id"]], "participants": ["gpt"]})
    assert response.status_code == 201, response.get_data(as_text=True)
    assert response.get_json()["created_count"] >= 1
    texts = [r[0] for r in sqlite3.connect(db).execute("SELECT text FROM proposed_interpretations")]
    assert texts and all(t == READING for t in texts)
